name: wayz
description: "A Flutter app for renting vehicles in a tourism context."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10  
  animated_text_kit: ^4.2.2       
  smooth_page_indicator: ^1.1.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.3.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^6.0.0
  cloudinary_public: ^0.21.0
  image_picker: ^1.0.7
  fl_chart: ^0.65.0
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  flutter_datetime_picker_plus: ^2.1.0
  onesignal_flutter: ^5.3.3
  http: ^1.4.0  
  share_plus: ^7.2.1
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.8.0
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#051B45"
  adaptive_icon_foreground: "assets/icon/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#051B45"
    theme_color: "#051B45"
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/car logo/
    - assets/images/
    - assets/images/splash_background.png
    - assets/images/logo.png
    - assets/images/login_background.jpg
    - assets/images/signup_background.jpg
    - assets/images/road_background.jpg
    - assets/images/  # Add this line to include all images in the directory
    - assets/icon/  # If you have an icons directory

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

dependency_overrides:
  carousel_slider: 4.2.1  # Use the version you're currently using
