// This is a simplified version - normally this file is generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Values extracted from your google-services.json file
    return const FirebaseOptions(
      apiKey: 'AIzaSyB8zdbH32dE_6CVEEb7HACuWFyLkZqwiP0',
      appId: '1:112419920911:android:3db434901fc1dc6f51577a',
      messagingSenderId: '112419920911',
      projectId: 'vehicle-rental-app-aba3c',
      storageBucket: 'vehicle-rental-app-aba3c.firebasestorage.app',
    );
  }
}
