// File generated by FlutterFire CLI.
import 'dart:io';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM0Ltd6pXEQOGypvr4-_1Oha5Ce37lQZ8',
    appId: '1:921265432897:web:164eef49bbc692778759c0',
    messagingSenderId: '921265432897',
    projectId: 'wayz-e430e',
    authDomain: 'wayz-e430e.firebaseapp.com',
    storageBucket: 'wayz-e430e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM0Ltd6pXEQOGypvr4-_1Oha5Ce37lQZ8',
    appId: '1:921265432897:android:164eef49bbc692778759c0',
    messagingSenderId: '921265432897',
    projectId: 'wayz-e430e',
    storageBucket: 'wayz-e430e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0Ltd6pXEQOGypvr4-_1Oha5Ce37lQZ8', // Same API key can usually be used
    appId: '1:921265432897:ios:164eef49bbc692778759c0',
    messagingSenderId: '921265432897',
    projectId: 'wayz-e430e',
    storageBucket: 'wayz-e430e.firebasestorage.app',
    // Note: You should create proper GoogleService-Info.plist for iOS
  );
}
