#!/bin/bash
# Day 3: Environment Configuration Script

echo "🚀 Tourism Vehicle Rental - Day 3 Database Setup"
echo "=================================================="
echo ""
echo "1. After setting up Railway, you'll get connection strings like:"
echo ""
echo "PostgreSQL URL: postgresql://postgres:XXXXX@containers-us-west-xyz.railway.app:5432/railway"
echo "Redis URL: redis://default:XXXXX@containers-us-west-xyz.railway.app:6379"
echo ""
echo "2. Extract the following values from your PostgreSQL URL:"
echo "   - Host: containers-us-west-xyz.railway.app"
echo "   - Port: 5432"  
echo "   - Username: postgres"
echo "   - Password: XXXXX (the part after postgres:)"
echo "   - Database: railway"
echo ""
echo "3. Extract the following values from your Redis URL:"
echo "   - Host: containers-us-west-xyz.railway.app"
echo "   - Port: 6379"
echo "   - Password: XXXXX (the part after default:)"
echo ""
echo "4. Update your .env file with these values"
echo ""
echo "Need help? Run this script with your connection strings as arguments!"
